update portti_view_bundle_seq set config = '
{
   "globalMapAjaxUrl":"[REPLACEDBYHANDLER]",
   "plugins":[
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.LayersPlugin"
      },
	  {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.LayersLoadingPlugin"
      },
      {
         "id":"Oskari.mapframework.mapmodule.WmsLayerPlugin"
      },
      {
         "id":"Oskari.mapframework.mapmodule.MarkersPlugin"
      },
      {
         "id":"Oskari.mapframework.mapmodule.ControlsPlugin"
      },
      {
         "config":{
            "ignoredLayerTypes":[
               "WFS",
               "STATS"
            ]
         },
         "id":"Oskari.mapframework.mapmodule.GetInfoPlugin"
      },
      {
         "id":"Oskari.mapframework.wmts.mapmodule.plugin.WmtsLayerPlugin"
      },
      {
         "id":"Oskari.arcgis.bundle.maparcgis.plugin.ArcGisLayerPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapwfs2.plugin.WfsLayerPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.ScaleBarPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.MapIconsPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.BackgroundDrawPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.Portti2Zoombar"
      },
      {
         "id":"Oskari.mapframework.bundle.mapstats.plugin.StatsLayerPlugin",
         "config":{
            "useArcGis":true
         }
      },
      {
         "id":"Oskari.mapframework.bundle.mapmodule.plugin.LogoPlugin",
         "config":{
            "termsUrl":{
               "fi":"http://gagmin.com/wp-content/uploads/2013/10/philosoraptor_meme_if_a_vampire_bites_a_zombie_will_it_turn_into_a_zombie_or_will_the_zombie_turn_into_a_vampire-1.jpg",
               "sv":"http://gagmin.com/wp-content/uploads/2013/10/philosoraptor_meme_if_a_vampire_bites_a_zombie_will_it_turn_into_a_zombie_or_will_the_zombie_turn_into_a_vampire-1.jpg",
               "en":"http://gagmin.com/wp-content/uploads/2013/10/philosoraptor_meme_if_a_vampire_bites_a_zombie_will_it_turn_into_a_zombie_or_will_the_zombie_turn_into_a_vampire-1.jpg"
            }
         }
      },
      {
         "id":"Oskari.mapframework.bundle.mapanalysis.plugin.AnalysisLayerPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.mapmyplaces.plugin.MyPlacesLayerPlugin"
      },
      {
         "id":"Oskari.mapframework.bundle.myplacesimport.plugin.UserLayersLayerPlugin"
      }
   ],
   "mapOptions":{
      "resolutions":[
         2048,
         1024,
         512,
         256,
         128,
         64,
         32,
         16,
         8,
         4,
         2,
         1,
         0.5,
         0.25
      ],
      "maxExtent":{
         "left":-548576.000000,
         "bottom":6291456.000000,
         "right":1548576.000000,
         "top":8388608.000000
      },
      "srsName":"EPSG:3067"
   },
   "layers":[
      {
         "id":10
      }
   ],
   "imageLocation":"/Oskari/resources"
}
'
where view_id = 1 and bundle_id = 5